name: 'ExtraItems'
version: '1.0'
api-version: '1.16'
main: 'eu.bebendorf.extraitems.ExtraItemsPlugin'
commands:
  extraitems:
    aliases: ['eitems']
    description: 'Gibt dir spezielle Items'
    permission: 'extraitems.give'